### ISSUE TITLE
Add Expense

### ISSUE THREAD

**Issue by PLUCS2** [rachanavishwanath/SmartSplit#7]
- [x] `All Expenses` Breaks the App
- [x] When you are on user 2's page and you add an expense with user 1 it shows up on user 2's page. It is only there until you navigate away - but shouldn't be there at all
- [x] Add the errors (for if a user tries to save without adding in a description or cost

Excellent work!

**Comment by rachanavishwanath** [comment]
These are fixed now. Closing the issue.
